/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur;

import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author zhangxi
 */
public class FGestionSalons extends javax.swing.JFrame {

    /**
     * Creates new form FGestionSalons
     */
    private Controleur controleur;
    private java.awt.Frame parent;
    private DefaultListModel listeSalonLance;
    private DefaultListModel listeSalonNonLance;
    //private HashMap<String, TheadSalon> theadSalons;

    public FGestionSalons(java.awt.Frame parent, Controleur controleur) {
        //this.theadSalons = new HashMap<String, TheadSalon>();
        this.setControleur(controleur);
        this.parent = parent;
        setBounds(400, 300, 391, 353);
        initComponents();
    }

    public Controleur getControleur() {
        return controleur;
    }

    public void setControleur(Controleur controleur) {
        this.controleur = controleur;
    }

    public void init() {
        listeSalonLance = new DefaultListModel();
        listeSalonNonLance = new DefaultListModel();
        for (String key : this.controleur.getSalonsNonLancer().keySet()) {
            listeSalonNonLance.addElement(key);
        }
        for (String key : this.controleur.getSalons().keySet()) {
            listeSalonLance.addElement(key);
        }

        this.jListLance = new JList(listeSalonLance);
        jScrollPane2.setViewportView(jListLance);
        this.jListNonLance = new JList(listeSalonNonLance);
        jScrollPane1.setViewportView(jListNonLance);
        if (listeSalonLance.isEmpty()) {
            jButtonFermer.setEnabled(false);
        } else {
            jButtonFermer.setEnabled(true);
            jListLance.setSelectedIndex(0);
        }
        if (listeSalonNonLance.isEmpty()) {
            jButtonOuvrir.setEnabled(false);
        } else {
            jListNonLance.setSelectedIndex(0);
            jButtonOuvrir.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListNonLance = new javax.swing.JList();
        jButtonOuvrir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLance = new javax.swing.JList();
        jTextFieldNouveauSalon = new javax.swing.JTextField();
        jButtonFermer = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Gestion Des Salons");

        jListNonLance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListNonLance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jListNonLance);

        jButtonOuvrir.setText("Ouvrir>>>");
        jButtonOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOuvrirActionPerformed(evt);
            }
        });

        jListLance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListLance);

        jButtonFermer.setText("<<<Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Créer");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom du salon :");

        jLabel2.setText("Salon(s) fermé(s) :");

        jLabel3.setText("Salon(s) ouvert(s) :");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldNouveauSalon)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAjouter))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonOuvrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonFermer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(235, 235, 235)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNouveauSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouter))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButtonOuvrir)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonFermer))
                    .addComponent(jScrollPane2))
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOuvrirActionPerformed
        // TODO add your handling code here:
        controleur.ouvrirUnSalon(jListNonLance.getSelectedValue().toString());
        init();
    }//GEN-LAST:event_jButtonOuvrirActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldNouveauSalon.getText().isEmpty()) {
            if (!listeSalonNonLance.contains(jTextFieldNouveauSalon.getText()) && !listeSalonLance.contains(jTextFieldNouveauSalon.getText())) {
                controleur.setSalonNonLancer(new Salon(jTextFieldNouveauSalon.getText()), jTextFieldNouveauSalon.getText());
                listeSalonNonLance.addElement(jTextFieldNouveauSalon.getText());
                jButtonOuvrir.setEnabled(true);
                jListNonLance.setSelectedIndex(0);
            } else {
                MessageBox mb = new MessageBox(this, true, "Le nom du salon déjà existe !");
                mb.setVisible(true);
            }
        } else {
            MessageBox mb = new MessageBox(this, true, "Vous devez donner un nom pour creer un salon ?");
            mb.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        controleur.fermerUnSalon(jListLance.getSelectedValue().toString());
        init();
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonOuvrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListLance;
    private javax.swing.JList jListNonLance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldNouveauSalon;
    // End of variables declaration//GEN-END:variables
}
