/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur;

/**
 *
 * @author zhangxi
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    private Controleur controleur;
    private FGestionSalons fGest;

    public FPrincipal(Controleur controleur) {
        this.fGest = new FGestionSalons (this,controleur);
        fGest.init();
        this.setControleur(controleur);
        setBounds(400, 300, 391, 353);
        initComponents();
    }

    public Controleur getControleur() {
        return controleur;
    }

    public void setControleur(Controleur controleur) {
        this.controleur = controleur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDemmarer = new javax.swing.JMenuItem();
        jMenuItemStopper = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemGestionSalons = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serveur Chat");

        jMenu1.setText("Serveur");

        jMenuItemDemmarer.setText("Démarrer le serveur");
        jMenuItemDemmarer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDemmarerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDemmarer);

        jMenuItemStopper.setText("Stopper le serveur");
        jMenuItemStopper.setEnabled(false);
        jMenuItemStopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStopperActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemStopper);
        jMenu1.add(jSeparator4);

        jMenuItemQuitter.setText("Quitter");
        jMenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemQuitter);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salons");

        jMenuItemGestionSalons.setText("Gestion des salons");
        jMenuItemGestionSalons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionSalonsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGestionSalons);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemStopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStopperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemStopperActionPerformed

    private void jMenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemQuitterActionPerformed

    private void jMenuItemGestionSalonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionSalonsActionPerformed
        // TODO add your handling code here:
        fGest.setVisible(true);

    }//GEN-LAST:event_jMenuItemGestionSalonsActionPerformed

    private void jMenuItemDemmarerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDemmarerActionPerformed
        // TODO add your handling code here:
        TheadSalon ts = new TheadSalon(controleur, controleur.getNomPremierSalon());
        ts.start();
        fGest.setTheadSalon(ts,controleur.getNomPremierSalon());
        this.jMenuItemDemmarer.setEnabled(false);
        this.jMenuItemStopper.setEnabled(true);
    }//GEN-LAST:event_jMenuItemDemmarerActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDemmarer;
    private javax.swing.JMenuItem jMenuItemGestionSalons;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenuItem jMenuItemStopper;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
