/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetclientserveur;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author bodinjo
 */
public class FInscription extends javax.swing.JFrame {

    private Controleur controleur;
    /**
     * Creates new form Inscription
     */
    private java.awt.Frame parent;
    private String login;
    private String mdp;
    private String email;
    private String dateNais;
    private boolean sexe;

    public FInscription(java.awt.Frame parent, Controleur controleur) {
        this.setControleur(controleur);
        setBounds(400, 300, 391, 353);
        initComponents();
        parent.setVisible(false);
        this.parent = parent;

    }

    public Controleur getControleur() {
        return controleur;
    }

    public void setControleur(Controleur controleur) {
        this.controleur = controleur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonVerifier = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDateNaiss = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonFille = new javax.swing.JRadioButton();
        jRadioButtonGarcon = new javax.swing.JRadioButton();
        jButtonInscription = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("projetclientserveur/Bundle"); // NOI18N
        setTitle(bundle.getString("INSCRIPTION")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText(bundle.getString("NOM UTILISATEUR :")); // NOI18N

        jTextFieldLogin.setForeground(java.awt.Color.lightGray);
        jTextFieldLogin.setText(bundle.getString("CHOISIR UN LOGIN")); // NOI18N
        jTextFieldLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLoginFocusLost(evt);
            }
        });
        jTextFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLoginKeyTyped(evt);
            }
        });

        jButtonVerifier.setText(bundle.getString("VÉRIFIER")); // NOI18N
        jButtonVerifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerifierActionPerformed(evt);
            }
        });

        jButtonQuitter.setText(bundle.getString("QUITTER")); // NOI18N
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("MOT DE PASSE :")); // NOI18N

        jLabel3.setText(bundle.getString("CONFIRMATION :")); // NOI18N

        jLabel4.setText(bundle.getString("ADRESSE EMAIL :")); // NOI18N

        jTextFieldEmail.setForeground(java.awt.Color.lightGray);
        jTextFieldEmail.setText(bundle.getString("EXEMPLE@EXEMPLE.FR")); // NOI18N
        jTextFieldEmail.setEnabled(false);
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });

        jLabel5.setText(bundle.getString("DATE DE NAISSANCE :")); // NOI18N

        jTextFieldDateNaiss.setForeground(java.awt.Color.lightGray);
        jTextFieldDateNaiss.setText(bundle.getString("01/01/2000")); // NOI18N
        jTextFieldDateNaiss.setEnabled(false);
        jTextFieldDateNaiss.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateNaissFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDateNaissFocusLost(evt);
            }
        });
        jTextFieldDateNaiss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDateNaissKeyTyped(evt);
            }
        });

        jLabel6.setText(bundle.getString("SEXE :")); // NOI18N

        buttonGroup1.add(jRadioButtonFille);
        jRadioButtonFille.setSelected(true);
        jRadioButtonFille.setText(bundle.getString("FILLE")); // NOI18N
        jRadioButtonFille.setEnabled(false);

        buttonGroup1.add(jRadioButtonGarcon);
        jRadioButtonGarcon.setText(bundle.getString("GARÇON")); // NOI18N
        jRadioButtonGarcon.setEnabled(false);

        jButtonInscription.setText(bundle.getString("INSCRIPTION")); // NOI18N
        jButtonInscription.setEnabled(false);
        jButtonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscriptionActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText(bundle.getString("ANNULER")); // NOI18N
        jButtonAnnuler.setEnabled(false);
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jPasswordField1.setEnabled(false);

        jPasswordField2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButtonAnnuler)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInscription))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel6)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonGarcon)
                            .addComponent(jRadioButtonFille)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonQuitter)
                .addGap(18, 18, 18)
                .addComponent(jButtonVerifier)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonQuitter)
                    .addComponent(jButtonVerifier))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addComponent(jTextFieldDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(jRadioButtonFille))
                .addGap(6, 6, 6)
                .addComponent(jRadioButtonGarcon)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAnnuler)
                    .addComponent(jButtonInscription))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerifierActionPerformed
        if (jTextFieldLogin.getForeground() != Color.LIGHT_GRAY) {
            if (!jTextFieldLogin.getText().isEmpty()) {
                login = jTextFieldLogin.getText();
                if (getControleur().testLogin(login)) {
                    jButtonQuitter.setEnabled(false);
                    jButtonVerifier.setEnabled(false);
                    jTextFieldLogin.setEnabled(false);
                    jTextFieldEmail.setEnabled(true);
                    jPasswordField1.setEnabled(true);
                    jPasswordField2.setEnabled(true);
                    jTextFieldDateNaiss.setEnabled(true);
                    jRadioButtonFille.setEnabled(true);
                    jRadioButtonGarcon.setEnabled(true);
                    jButtonAnnuler.setEnabled(true);
                    jButtonInscription.setEnabled(true);
                } else {
                    MessageBox mb = new MessageBox(this, true, java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("NOM D'UTILISATEUR DÉJÀ UTILISÉ"));
                    mb.setVisible(true);
                }
            } else {
                MessageBox mb = new MessageBox(this, true, java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("CHAMPS LOGIN VIDE"));
                mb.setVisible(true);
            }
        } else {
            MessageBox mb = new MessageBox(this, true, java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("CHAMPS LOGIN VIDE"));
            mb.setVisible(true);
        }
        jPasswordField1.requestFocusInWindow();
    }//GEN-LAST:event_jButtonVerifierActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        jButtonQuitter.setEnabled(true);
        jButtonVerifier.setEnabled(true);
        jTextFieldLogin.setEnabled(true);
        jTextFieldEmail.setEnabled(false);
        jPasswordField1.setEnabled(false);
        jPasswordField2.setEnabled(false);
        jTextFieldDateNaiss.setEnabled(false);
        jRadioButtonFille.setEnabled(false);
        jRadioButtonGarcon.setEnabled(false);
        jButtonAnnuler.setEnabled(false);
        jButtonInscription.setEnabled(false);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscriptionActionPerformed
        mdp = new String(jPasswordField1.getPassword());
        if (mdp.equals(new String(jPasswordField2.getPassword()))) {
            email = jTextFieldEmail.getText();
            dateNais = jTextFieldDateNaiss.getText();
            if (jRadioButtonFille.isSelected()) {
                sexe = false;
            } else {
                sexe = true;
            }
            if (!mdp.isEmpty() && !email.isEmpty() && !dateNais.isEmpty() &&
                    jTextFieldEmail.getForeground() == Color.black && jTextFieldDateNaiss.getForeground() == Color.black) {
                if (getControleur().inscrire(login, mdp, email, dateNais, sexe)) {
                    MessageBox mb = new MessageBox(this, true, java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("L'UTILISATEUR : {0} EST INSCRIT"), new Object[] {login}));
                    mb.setVisible(true);
                    this.dispose();
                    parent.setVisible(true);
                } else {
                    MessageBox mb = new MessageBox(this, true, java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("PROBLÈME CONNECTION SERVEUR INSCRIPTION"));
                    mb.setVisible(true);
                }
            } else {
                MessageBox mb = new MessageBox(this, true, java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("CHAMP(S) VIDE(S)"));
                mb.setVisible(true);
            }
        } else {
            MessageBox mb = new MessageBox(this, true, java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("MOT DE PASSE DIFFÉRENT"));
            mb.setVisible(true);
        }
    }//GEN-LAST:event_jButtonInscriptionActionPerformed

    private void jTextFieldLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLoginFocusGained
        if (jTextFieldLogin.getForeground() == Color.LIGHT_GRAY) {
            jTextFieldLogin.setText(null);
            jTextFieldLogin.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldLoginFocusGained

    private void jTextFieldLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLoginFocusLost
        if (jTextFieldLogin.getText().isEmpty()) {
            jTextFieldLogin.setForeground(Color.LIGHT_GRAY);
            jTextFieldLogin.setText(java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("CHOISIR UN LOGIN"));
        }
    }//GEN-LAST:event_jTextFieldLoginFocusLost

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        if (jTextFieldEmail.getForeground() == Color.LIGHT_GRAY) {
            jTextFieldEmail.setText(null);
            jTextFieldEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        if (jTextFieldEmail.getText().isEmpty()) {
            jTextFieldEmail.setForeground(Color.LIGHT_GRAY);
            jTextFieldEmail.setText(java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("EXEMPLE@EXEMPLE.COM"));
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldDateNaissFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateNaissFocusGained
        if (jTextFieldDateNaiss.getForeground() == Color.LIGHT_GRAY) {
            jTextFieldDateNaiss.setText(null);
            jTextFieldDateNaiss.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldDateNaissFocusGained

    private void jTextFieldDateNaissFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateNaissFocusLost
        if (jTextFieldDateNaiss.getText().isEmpty()) {
            jTextFieldDateNaiss.setForeground(Color.LIGHT_GRAY);
            jTextFieldDateNaiss.setText(java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("01/01/2000"));
        }
    }//GEN-LAST:event_jTextFieldDateNaissFocusLost

    private void jTextFieldLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoginKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER && !jTextFieldLogin.getText().isEmpty()) {
            jButtonVerifier.doClick();
        }
    }//GEN-LAST:event_jTextFieldLoginKeyTyped

    private void jTextFieldDateNaissKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateNaissKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER && !jTextFieldDateNaiss.getText().isEmpty()) {
            jButtonInscription.doClick();
        }
    }//GEN-LAST:event_jTextFieldDateNaissKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonInscription;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonVerifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButtonFille;
    private javax.swing.JRadioButton jRadioButtonGarcon;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldDateNaiss;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}