/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetclientserveur;

import java.awt.event.KeyEvent;
import java.util.Locale;
import javax.swing.*;

/**
 * <p> FPrincipal est la classe qui créé la fenetre principal où l'ont peut
 * atteindre les différentes fonction du programme</p>
 *
 * @author J. Bodin et X. Zhang
 * @version 1.0
 */
public class FPrincipal extends javax.swing.JFrame {

    private DefaultListModel listeSalon;
    private Controleur controleur;

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal(Controleur controleur) {

        this.listeSalon = new DefaultListModel();
        this.setControleur(controleur);
        setBounds(400, 300, 391, 353);
        initComponents();
        jScrollPane1.setVisible(false);
        jButtonActualiser.setVisible(false);
        jButtonEntrer.setVisible(false);
        jButtonEntrer.setEnabled(false);
    }

    /**
     * Retourne le controleur de l'application
     *
     * @return Le controleur
     * @see Controleur
     */
    public Controleur getControleur() {
        return controleur;
    }

    /**
     * Met à jour le controleur
     *
     * @param controleur Le controleur
     * @see Controleur *
     */
    public void setControleur(Controleur controleur) {
        this.controleur = controleur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonEntrer = new javax.swing.JButton();
        jButtonActualiser = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mSession = new javax.swing.JMenu();
        mItemInscription = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mItemConnection = new javax.swing.JMenuItem();
        mItemDeconnection = new javax.swing.JMenuItem();
        mItemQuitter = new javax.swing.JMenuItem();
        mAide = new javax.swing.JMenu();
        menuLangue = new javax.swing.JMenu();
        butDeutsch = new javax.swing.JMenuItem();
        butEnglish = new javax.swing.JMenuItem();
        butEspañol = new javax.swing.JMenuItem();
        butFrancais = new javax.swing.JMenuItem();
        butNederlands = new javax.swing.JMenuItem();
        butItaliano = new javax.swing.JMenuItem();
        butChinois = new javax.swing.JMenuItem();
        mItemServeur = new javax.swing.JMenuItem();
        jMenuDoc = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("projetclientserveur/Bundle"); // NOI18N
        setTitle(bundle.getString("PROJET CLIENT SERVEUR")); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jList1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButtonEntrer.setText(bundle.getString("Entrer")); // NOI18N
        jButtonEntrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrerActionPerformed(evt);
            }
        });

        jButtonActualiser.setText(bundle.getString("Actualiser")); // NOI18N
        jButtonActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualiserActionPerformed(evt);
            }
        });

        mSession.setText(bundle.getString("SESSION")); // NOI18N

        mItemInscription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mItemInscription.setText(bundle.getString("INSCRIPTION")); // NOI18N
        mItemInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemInscriptionActionPerformed(evt);
            }
        });
        mSession.add(mItemInscription);
        mSession.add(jSeparator1);

        mItemConnection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mItemConnection.setText(bundle.getString("CONNECTION")); // NOI18N
        mItemConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemConnectionActionPerformed(evt);
            }
        });
        mSession.add(mItemConnection);

        mItemDeconnection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mItemDeconnection.setText(bundle.getString("DECONNECTION")); // NOI18N
        mItemDeconnection.setEnabled(false);
        mItemDeconnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDeconnectionActionPerformed(evt);
            }
        });
        mSession.add(mItemDeconnection);

        mItemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mItemQuitter.setText(bundle.getString("QUITTER")); // NOI18N
        mItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemQuitterActionPerformed(evt);
            }
        });
        mSession.add(mItemQuitter);

        jMenuBar1.add(mSession);

        mAide.setText(bundle.getString("OPTION")); // NOI18N

        menuLangue.setText("Changer langue ");

        butDeutsch.setText("Deutsch");
        butDeutsch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDeutschActionPerformed(evt);
            }
        });
        menuLangue.add(butDeutsch);

        butEnglish.setText("English");
        butEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEnglishActionPerformed(evt);
            }
        });
        menuLangue.add(butEnglish);

        butEspañol.setText("Español");
        butEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEspañolActionPerformed(evt);
            }
        });
        menuLangue.add(butEspañol);

        butFrancais.setText("Français");
        butFrancais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFrancaisActionPerformed(evt);
            }
        });
        menuLangue.add(butFrancais);

        butNederlands.setText("Nederlands");
        butNederlands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNederlandsActionPerformed(evt);
            }
        });
        menuLangue.add(butNederlands);

        butItaliano.setText("Italiano");
        butItaliano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butItalianoActionPerformed(evt);
            }
        });
        menuLangue.add(butItaliano);

        butChinois.setText("中文 ");
        butChinois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butChinoisActionPerformed(evt);
            }
        });
        menuLangue.add(butChinois);

        mAide.add(menuLangue);

        mItemServeur.setText(bundle.getString("CHANGER SERVEUR")); // NOI18N
        mItemServeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemServeurActionPerformed(evt);
            }
        });
        mAide.add(mItemServeur);

        jMenuDoc.setText(bundle.getString("AIDE")); // NOI18N
        jMenuDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDocActionPerformed(evt);
            }
        });
        mAide.add(jMenuDoc);

        jMenuBar1.add(mAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonActualiser)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEntrer))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualiser)
                    .addComponent(jButtonEntrer))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemQuitterActionPerformed
        MessageBox mb = new MessageBox(this, true, java.util.ResourceBundle.getBundle("projetclientserveur/Bundle").getString("QUITTER ?"));
        mb.setVisible(true);
    }//GEN-LAST:event_mItemQuitterActionPerformed

    private void mItemInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemInscriptionActionPerformed
        getControleur().fenetreInscription();
    }//GEN-LAST:event_mItemInscriptionActionPerformed

    private void mItemConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemConnectionActionPerformed
        getControleur().fenetreConnection();
    }

    public JButton getjButtonEntrer() {
        return jButtonEntrer;
    }

    public JButton getjButtonActualiser() {
        return jButtonActualiser;
    }

    public JList getjList1() {
        return jList1;
    }

    public void setjList1(JList jList1) {
        this.jList1 = jList1;
    }

    public void setListeSalon(DefaultListModel listeSalon) {
        this.listeSalon = listeSalon;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public DefaultListModel getListeSalon() {
        return listeSalon;
    }

    public JMenuItem getMItemConnection() {
        return mItemConnection;
    }

    public JMenuItem getMItemInscription() {
        return mItemInscription;
    }

    public JMenuItem getMItemQuitter() {
        return mItemQuitter;
    }//GEN-LAST:event_mItemConnectionActionPerformed

    public JMenuItem getMItemDeconnection() {
        return mItemDeconnection;
    }

    public JMenuItem getMItemServeur() {
        return mItemServeur;
    }

    public JMenu getMenuLangue() {
        return menuLangue;
    }

    public JMenuItem getmItemConnection() {
        return mItemConnection;
    }

    public JMenuItem getmItemDeconnection() {
        return mItemDeconnection;
    }

    public JMenuItem getmItemInscription() {
        return mItemInscription;
    }

    private void mItemDeconnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDeconnectionActionPerformed
        this.controleur.deconnection();

    }//GEN-LAST:event_mItemDeconnectionActionPerformed

    private void jMenuDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDocActionPerformed
        getControleur().fenetreAide();
    }//GEN-LAST:event_jMenuDocActionPerformed

    private void mItemServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemServeurActionPerformed
        getControleur().fenetreServeur();
    }//GEN-LAST:event_mItemServeurActionPerformed

    private void butFrancaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFrancaisActionPerformed
        // TODO add your handling code here:
        getControleur().setLangue(new Locale("fr", "FR", ""));
    }//GEN-LAST:event_butFrancaisActionPerformed

    private void butChinoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butChinoisActionPerformed
        // TODO add your handling code here:
        getControleur().setLangue(new Locale("zh", "CN", ""));
    }//GEN-LAST:event_butChinoisActionPerformed

    private void butEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEspañolActionPerformed
        // TODO add your handling code here:
        getControleur().setLangue(new Locale("es", "ES", ""));
    }//GEN-LAST:event_butEspañolActionPerformed

    private void butItalianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butItalianoActionPerformed
        // TODO add your handling code here:
        getControleur().setLangue(new Locale("it", "IT", ""));
    }//GEN-LAST:event_butItalianoActionPerformed

    private void butNederlandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNederlandsActionPerformed
        // TODO add your handling code here:
        getControleur().setLangue(new Locale("nl", "NL", ""));
    }//GEN-LAST:event_butNederlandsActionPerformed

    private void butDeutschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDeutschActionPerformed
        // TODO add your handling code here:
        getControleur().setLangue(new Locale("de", "DE", ""));
    }//GEN-LAST:event_butDeutschActionPerformed

    private void butEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEnglishActionPerformed
        // TODO add your handling code here:
        getControleur().setLangue(new Locale("en", "US", ""));
    }//GEN-LAST:event_butEnglishActionPerformed

    private void jButtonEntrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrerActionPerformed
        System.out.println("vous allez entrer dans : " + jList1.getSelectedValue().toString());
        controleur.fenetreSalon(jList1.getSelectedValue().toString());
        jButtonEntrer.setEnabled(false);
    }//GEN-LAST:event_jButtonEntrerActionPerformed

    private void jButtonActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualiserActionPerformed

        controleur.actualiser();
    }//GEN-LAST:event_jButtonActualiserActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {


            jButtonEntrer.doClick();
        }
    }//GEN-LAST:event_formKeyTyped

    private void jList1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {


            jButtonEntrer.doClick();
        }
    }//GEN-LAST:event_jList1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem butChinois;
    private javax.swing.JMenuItem butDeutsch;
    private javax.swing.JMenuItem butEnglish;
    private javax.swing.JMenuItem butEspañol;
    private javax.swing.JMenuItem butFrancais;
    private javax.swing.JMenuItem butItaliano;
    private javax.swing.JMenuItem butNederlands;
    private javax.swing.JButton jButtonActualiser;
    private javax.swing.JButton jButtonEntrer;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDoc;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mAide;
    private javax.swing.JMenuItem mItemConnection;
    private javax.swing.JMenuItem mItemDeconnection;
    private javax.swing.JMenuItem mItemInscription;
    private javax.swing.JMenuItem mItemQuitter;
    private javax.swing.JMenuItem mItemServeur;
    private javax.swing.JMenu mSession;
    private javax.swing.JMenu menuLangue;
    // End of variables declaration//GEN-END:variables
}
